import Head from "next/head";
import { GetServerSideProps } from "next";
import { DefaultSession, getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Image from "next/image";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";

type HomeProps = {
    user: DefaultSession["user"] | null;
};

export default function Home({ user }: HomeProps) {
    return (
        <>
            <Head>
                <title>Home - TuneTracer</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container my-20">
                <>
                    <h1 className="text-5xl sm:text-6xl font-bold">TuneTracer</h1>
                    {user ? <h2>You&apos;re connected ✅</h2> : <h2>You&apos;re not connected ❌</h2>}
                    <Card className="my-6">
                        <CardHeader className="pl-20">
                            <CardTitle>Historical Data</CardTitle>
                        </CardHeader>
                        <CardContent className="overflow-hidden sm:flex items-center justify-center">
                            <Image
                                className="float-left sm:float-none w-40 h-40 md:w-auto md:h-auto"
                                priority={true}
                                quality={100}
                                src="/spotify-logo.png"
                                alt="Spotify Logo"
                                width={250}
                                height={250}
                                draggable="false"
                            />
                            <p>
                                Explore your top-played songs, artists, and musical preferences, and easily toggle
                                between three distinct time intervals.
                            </p>
                        </CardContent>
                    </Card>

                    <Card className="my-6">
                        <CardHeader className="pl-20">
                            <CardTitle>Create Playlist</CardTitle>
                        </CardHeader>
                        <CardContent className="overflow-hidden sm:flex items-center justify-center">
                            <Image
                                className="float-left sm:float-none w-40 h-40 md:w-auto md:h-auto"
                                priority={true}
                                quality={100}
                                src="/notify-heart-dynamic-gradient.png"
                                alt="Playlist Logo"
                                width={250}
                                height={250}
                                draggable="false"
                            />
                            <p>
                                Generate a playlist using your personal charts with time and enjoy listening to it
                                directly within your Spotify application.
                            </p>
                        </CardContent>
                    </Card>
                </>
            </main>
        </>
    );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
    const session = await getServerSession(context.req, context.res, authOptions);

    if (!session) {
        return { props: { user: null } };
    }

    return {
        props: { user: session.user },
    };
};
