import Head from "next/head";
import { GetServerSideProps } from "next";
import { DefaultSession, getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import { Overview } from "@/components/ListenChart";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";

type HomeProps = {
  user: DefaultSession["user"] | null;
};

export default function Home({ user }: HomeProps) {
  return (
    <>
      <Head>
        <title>Home - TuneTracer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <>
          <h1>Hours Listened</h1>
          {user ? (
            <p>You&apos;re not connected ❌</p>
          ) : (
            <p>You&apos;re connected ✅</p>
          )}
          <Card className="my-6">
            <CardHeader>
              <CardTitle>Overview</CardTitle>
            </CardHeader>
            <CardContent className="pl-2">
              <Overview />
            </CardContent>
          </Card>
        </>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerSession(context.req, context.res, authOptions);

  if (!session) {
    return { props: { user: null } };
  }

  return {
    props: { user: session.user },
  };
};
