import { getServerSession } from "next-auth";
import { GetServerSideProps } from "next/types";
import { authOptions } from "./api/auth/[...nextauth]";
import PlayerSection from "@/components/PlayerSection";
import NextTrackList from "@/components/NextTrackList";
import Head from "next/head";

export default function Playing() {
    return (
        <>
            <Head>
                <title>Playing - TuneTracer</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container flex mt-12 justify-center">
                <div className="w-1/3 pt-8 px-4 hidden md:block">
                    <h2 className="text-4xl font-bold">Discover New Music</h2>
                    <div>
                        <h2>Top chart</h2>
                        <div className="flex flex-wrap">
                            <div className="w-1/2">
                                <img
                                    className="rounded"
                                    src="https://i.scdn.co/image/ab67616d000048512bc92df808bf68e6610513b3"
                                    alt="test"
                                />
                                <p>titre</p>
                                <p>artist</p>
                            </div>
                            <div className="w-1/2">
                                <img
                                    src="https://i.scdn.co/image/ab67616d000048512bc92df808bf68e6610513b3"
                                    alt="test"
                                />
                                <p>titre</p>
                                <p>artist</p>
                            </div>
                            <div className="w-1/2">
                                <img
                                    src="https://i.scdn.co/image/ab67616d000048512bc92df808bf68e6610513b3"
                                    alt="test"
                                />
                                <p>titre</p>
                                <p>artist</p>
                            </div>
                            <div className="w-1/2">
                                <img
                                    src="https://i.scdn.co/image/ab67616d000048512bc92df808bf68e6610513b3"
                                    alt="test"
                                />
                                <p>titre</p>
                                <p>artist</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div className="md:border-x md:w-1/3 flex flex-col md:bg-secondary pt-8 h-[94dvh]">
                    <PlayerSection />
                </div>
                <div className="w-1/3 pt-8 px-4 hidden md:block">
                    <h2 className="text-3xl font-bold">Track list</h2>
                    <div>
                        <p className="text-gray-400">Playing next</p>
                        <NextTrackList />
                    </div>
                </div>
            </main>
        </>
    );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
    const session = await getServerSession(context.req, context.res, authOptions);

    if (!session) {
        return {
            redirect: {
                destination: "/",
                permanent: false,
            },
        };
    }

    return {
        props: {},
    };
};
