import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import dynamic from "next/dynamic";
import { useSession } from "next-auth/react";
import MainWrapper from "@/components/MainWrapper";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
    const { data: session } = useSession();

    const Logout = dynamic(() => import("@/components/LogoutButton"), {
        ssr: false,
    });
    const Login = dynamic(() => import("@/components/LoginButton"), {
        ssr: false,
    });

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                {session ? (
                    <>
                        <Logout /> <MainWrapper session={session} />
                    </>
                ) : (
                    <>
                        <Login provider={"spotify"} />
                        <p>Vous devez être connecté pour accéder au contenu</p>
                    </>
                )}
            </main>
        </>
    );
}
